services:
  stats-db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    build: stat-service/stat
    ports:
      - "9090:9090"
    depends_on:
          - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"

#  ewm-db:
#    image: postgres:16.1
